CREATE TABLE SONG_LIST (
   SONG_ID INT NOT NULL auto_increment PRIMARY KEY
    ,SONG_NAME VARCHAR(20)
    ,SONG_ARTIST VARCHAR(20)
    ,SONG_ALBUM VARCHAR(20)
    ,SONG_TAG VARCHAR(80)
    ,SONG_TRAKNUM INT
    ,SONG_TITLEYN TINYINT(1)
    ,SONG_ALBUMART VARCHAR(20)
    ,SONG_PLAYCOUNT INT
);
